---
- name: PKI
  hosts: localhost
  tasks:
    - name: Setup CA
      include_tasks: ./playbooks/pki/ca.yml
    - name: Setup Global Certificates
      include_tasks: ./playbooks/pki/certs.yml
      loop:
        - name: admin
          template: ./playbooks/pki/admin.conf.j2
- name: Configure Workers
  hosts: worker-nodes
  become: yes
  vars:
    root_ca_key: "{{ hostvars['localhost']['generated_root_ca_key']}}"
    root_ca_crt: "{{ hostvars['localhost']['generated_root_ca_crt']}}"
  vars_files:
    - ./playbooks/kubernetes_binaries.yml
  tasks:
    - name: Set host architecture
      ansible.builtin.set_fact:
        host_arch: >-
          {{
            {
              'x86_64': 'amd64',
              'aarch64': 'arm64',
              'arm64': 'arm64'
            }[ansible_architecture]
          }}
    - name: kubelet
      include_tasks: ./playbooks/kubelet/playbook.yml
