
- name: Install
  include_tasks: ./playbooks/install_single_binary.yml
  vars:
    binary: 'containerd'
- name: Install Copy Service
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0700
  loop:
    - { src: './containerd.service', dest: '/etc/systemd/system/containerd.service'}
- name: Install SystemD Service
  systemd_service:
    name: containerd
    enabled: true
    state: started
    daemon_reload: true
  
