---
- name: Generate Kubeconfig
  block:
    - name: Generate tmp file for kubeconfig
      tempfile:
        state: file
      register: tmp_kubeconfig
    - name: Ensure kubectl is installed on localhost
      command: kubectl
    - name: Extract Certificate Data
      community.crypto.x509_certificate_info:
        path: "{{ generated_cert_crt }}"
      register: cert_data
    - name: kubectl config set-cluster
      command:
        argv:
          - kubectl
          - config
          - set-cluster
          - kubernetes-the-hard-way
          - --certificate-authority
          - "{{ root_ca_crt }}"
          - --embed-certs=true
          - --server=https://server.kubernetes.local:6443
          - --kubeconfig="{{ tmp_kubeconfig.path }}"
    - name: kubectl config set-credentials
      command:
        argv:
          - kubectl
          - config
          - set-credentials
          - "{{ cert_data.subject.commonName }}"
          - --client-certificate
          - "{{ generated_cert_crt }}"
          - --client-key
          - "{{ generated_cert_key }}"
          - --embed-certs=true
          - --kubeconfig="{{ tmp_kubeconfig.path }}"
    - name: kubectl config set-context default
      command:
        argv:
          - kubectl
          - config
          - set-context
          - default
          - --cluster
          - kubernetes-the-hard-way
          - --user="{{ cert_data.subject.commonName }}"
          - --kubeconfig="{{ tmp_kubeconfig.path }}"
    - name: kubectl config use-context default
      command:
        argv:
          - kubectl
          - config
          - use-context
          - default
          - --kubeconfig="{{ tmp_kubeconfig.path }}"
    - name: Slurp Kubeconfig
      slurp:
        src: "{{ tmp_kubeconfig.path }}"
      register: kubeconfig_content
    - name: Set kubeconfig fact
      set_fact:
        kubeconfig: "{{ kubeconfig_content.content | b64decode }}"
  always:
    - name: Remove tmp file
      file:
        path: "{{ tmp_kubeconfig.path }}"
        state: absent

